## Stochastic Gradient Descent with Logistic Regression from Scratch 

In [1]:
import pandas as pd
import numpy as np



In [2]:
from sklearn.datasets import load_wine
wine = load_wine()
X = wine.data

In [3]:

pd.DataFrame(X)

0     1     2     3      4     5     6     7     8      9     10  \
0    14.23  1.71  2.43  15.6  127.0  2.80  3.06  0.28  2.29   5.64  1.04   
1    13.20  1.78  2.14  11.2  100.0  2.65  2.76  0.26  1.28   4.38  1.05   
2    13.16  2.36  2.67  18.6  101.0  2.80  3.24  0.30  2.81   5.68  1.03   
3    14.37  1.95  2.50  16.8  113.0  3.85  3.49  0.24  2.18   7.80  0.86   
4    13.24  2.59  2.87  21.0  118.0  2.80  2.69  0.39  1.82   4.32  1.04   
..     ...   ...   ...   ...    ...   ...   ...   ...   ...    ...   ...   
173  13.71  5.65  2.45  20.5   95.0  1.68  0.61  0.52  1.06   7.70  0.64   
174  13.40  3.91  2.48  23.0  102.0  1.80  0.75  0.43  1.41   7.30  0.70   
175  13.27  4.28  2.26  20.0  120.0  1.59  0.69  0.43  1.35  10.20  0.59   
176  13.17  2.59  2.37  20.0  120.0  1.65  0.68  0.53  1.46   9.30  0.60   
177  14.13  4.10  2.74  24.5   96.0  2.05  0.76  0.56  1.35   9.20  0.61   

       11      12  
0    3.92  1065.0  
1    3.40  1050.0  
2    3.17  1185.0  
3    3.45  1480.0  
4    2.93   735.0  
..    ...     ...  
173  1.74   740.0  
174  1.56   750.0  
175  1.56   835.0  
176  1.62   840.0  
177  1.60   560.0  

[178 rows x 13 columns]

In [4]:
wine.feature_names

['alcohol',
 'malic_acid',
 'ash',
 'alcalinity_of_ash',
 'magnesium',
 'total_phenols',
 'flavanoids',
 'nonflavanoid_phenols',
 'proanthocyanins',
 'color_intensity',
 'hue',
 'od280/od315_of_diluted_wines',
 'proline']

In [5]:
wine.target_names

array(['class_0', 'class_1', 'class_2'], dtype='<U7')

In [6]:
from sklearn.datasets import load_wine
wine = load_wine()
X = wine.data[:, 6] # flavanoids
y = wine.target

print("X shape " , X.shape , " y shape  " , y.shape)

X shape  (178,)  y shape   (178,)


In [7]:
 z = pd.DataFrame(np.vstack((y,X)).T)

In [8]:
tz = z[(z[0] == 0) | (z[0] == 1)]

In [9]:
tz

0     1
0    0.0  3.06
1    0.0  2.76
2    0.0  3.24
3    0.0  3.49
4    0.0  2.69
..   ...   ...
125  1.0  2.65
126  1.0  3.15
127  1.0  2.24
128  1.0  2.45
129  1.0  1.75

[130 rows x 2 columns]

In [10]:
y = np.array(tz[0])

In [11]:
X = np.array(tz[1])

In [12]:
X

array([3.06, 2.76, 3.24, 3.49, 2.69, 3.39, 2.52, 2.51, 2.98, 3.15, 3.32,
       2.43, 2.76, 3.69, 3.64, 2.91, 3.14, 3.4 , 3.93, 3.03, 3.17, 2.41,
       2.88, 2.37, 2.61, 2.68, 2.94, 2.19, 2.97, 2.33, 3.25, 3.19, 2.69,
       2.74, 2.53, 2.98, 2.68, 2.43, 2.64, 3.04, 3.29, 2.68, 3.56, 2.63,
       3.  , 2.65, 3.17, 3.39, 2.92, 3.54, 3.27, 2.99, 3.74, 2.79, 2.9 ,
       2.78, 3.  , 3.23, 3.67, 0.57, 1.09, 1.41, 1.79, 3.1 , 1.75, 2.65,
       3.18, 2.  , 1.3 , 1.28, 1.02, 2.86, 1.84, 2.89, 2.14, 1.57, 2.03,
       1.32, 1.85, 2.55, 2.26, 2.53, 1.58, 1.59, 2.21, 1.94, 1.69, 1.61,
       1.69, 1.59, 1.5 , 1.25, 1.46, 2.25, 2.26, 2.27, 0.99, 2.5 , 3.75,
       2.99, 2.17, 1.36, 2.11, 1.64, 1.92, 1.84, 2.03, 1.76, 2.04, 2.92,
       2.58, 2.27, 2.03, 2.01, 2.29, 2.17, 1.6 , 2.09, 1.25, 1.64, 2.79,
       5.08, 2.13, 2.65, 3.03, 2.65, 3.15, 2.24, 2.45, 1.75])

In [13]:
type(X)

numpy.ndarray

In [14]:
X.shape

(130,)

In [15]:
y.shape

(130,)

In [16]:
y

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [19]:



n =len(y)
m = 0 
c = 0
LR = 0.001  # The learning Rate
epochs = 100 # no. of iterations for optimization
accuracy = 0 
# Define sigmoid function
def sigmoid(z):
 sig = 1/(1+np.exp(-z))
 return sig

# Performing Gradient Descent Optimization
# for every epoch

for epoch in range(1,epochs+1):
    for i in range(len(X)):
        #compute gradient w.r.t 'm' 
        gr_wrt_m = X[i] * (sigmoid((m * X[i]) + c) - y[i])
        
        #compute gradient w.r.t 'c'
        gr_wrt_c = sigmoid((m * X[i]) + c) - y[i]
        #update m, c
        m = m - LR * gr_wrt_m
        c = c - LR * gr_wrt_c
# At the end of all epochs we will be having optimum values of 'm' and 'c'
# So by using those optimum values of 'm' and 'c' we can perform predictions

print(" m and c values are  ",  m , c)

predictions = []
ylist = []

for i in range(len(X)):
    z = (m * X[i]) + c
    y_pred = sigmoid(z)
    if y_pred>=0.5:
        predictions.append(1)
    else:
        predictions.append(0)

# 'predictions' list will contain all the predicted class labels using optimum 'm' and 'c'

for k in range(len(X)):
    if ( predictions[k] ==  int(y[k]) ):
        accuracy = accuracy + 1
    else:
        continue
print(" Accuracy is  ", accuracy/n)




 m and c values are   -0.33726366838359234 0.8885819845836133
 Accuracy is   0.8076923076923077


In [20]:
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression 

X1 = X.reshape(-1,1)

model = LogisticRegression(solver='newton-cg', max_iter=10)
model.fit(X1, y)
pred = model.predict(X1)
accuracy = accuracy_score(y, pred)
print(accuracy)

0.8153846153846154


In [21]:
pred

array([0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 1., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0.,
       1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 0., 1., 0., 0., 1.,
       1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 0., 0., 1., 0., 0., 0., 0., 1., 1., 1.])

In [22]:
print(model.coef_ , model.intercept_)

[[-2.30630719]] [6.053263]


In [23]:
model.predict_proba(X1)

array([[0.73185156, 0.26814844],
       [0.57740871, 0.42259129],
       [0.80520863, 0.19479137],
       [0.88035004, 0.11964996],
       [0.53760469, 0.46239531],
       [0.85384954, 0.14615046],
       [0.43994904, 0.56005096],
       [0.43427455, 0.56572545],
       [0.69413708, 0.30586292],
       [0.77058275, 0.22941725],
       [0.83253165, 0.16746835],
       [0.38961364, 0.61038636],
       [0.57740871, 0.42259129],
       [0.92107261, 0.07892739],
       [0.91227185, 0.08772815],
       [0.65883141, 0.34116859],
       [0.76648012, 0.23351988],
       [0.85670417, 0.14329583],
       [0.95304732, 0.04695268],
       [0.71805776, 0.28194224],
       [0.77863523, 0.22136477],
       [0.37870166, 0.62129834],
       [0.64311311, 0.35688689],
       [0.35725116, 0.64274884],
       [0.4915505 , 0.5084495 ],
       [0.53186681, 0.46813319],
       [0.67420813, 0.32579187],
       [0.26845994, 0.73154006],
       [0.68921873, 0.31078127],
       [0.33635789, 0.66364211],
       [0.

In [24]:

  
# creating the dataframe
df = pd.DataFrame(
    {
     'orginally y': y,
      'our prediction ': predictions,
     'sklearn prediction' : pred
    })



In [25]:
df['new'] = np.where((df['our prediction '] == df['sklearn prediction']) , "Matched", "Not Matched")


In [26]:
with pd.option_context('display.max_rows', None,
                       'display.max_columns', None,
                       'display.precision', 3,
                       ):
    print(df)
    

     orginally y  our prediction   sklearn prediction          new
0            0.0                0                 0.0      Matched
1            0.0                0                 0.0      Matched
2            0.0                0                 0.0      Matched
3            0.0                0                 0.0      Matched
4            0.0                0                 0.0      Matched
5            0.0                0                 0.0      Matched
6            0.0                1                 1.0      Matched
7            0.0                1                 1.0      Matched
8            0.0                0                 0.0      Matched
9            0.0                0                 0.0      Matched
10           0.0                0                 0.0      Matched
11           0.0                1                 1.0      Matched
12           0.0                0                 0.0      Matched
13           0.0                0                 0.0      Mat